# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "home"
  pageref = "/"
  weight = 1

[[main]]
  name = "blog"
  pageRef = "blog"
  weight = 2

[[main]]
  name = "portfolio"
  pageRef = "portfolio"
  weight = 3

[[main]]
  name = "lab"
  url = "/lab/root.html"
  weight = 4

[[main]]
  name = "links"
  pageRef = "link"
  weight = 5

[[main]]
  name = "about"
  url = "/whois/osgav.html"
  weight = 6

[[main]]
  name = "now"
  pageRef = "now"
  weight = 7


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "home"
  pageref = "home"
  url = "/"
  weight = 1

[[footer]]
  name = "blog"
  pageRef = "blog"
  weight = 2

[[footer]]
  name = "portfolio"
  pageRef = "portfolio"
  weight = 3

[[footer]]
  name = "lab"
  url = "/lab/root.html"
  weight = 4

[[footer]]
  name = "links"
  pageRef = "link"
  weight = 5

[[footer]]
  name = "about"
  url = "/whois/osgav.html"
  weight = 6

[[footer]]
  name = "now"
  pageRef = "now"
  weight = 7

