language: go
go:
- 1.4
install:
- wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz
- tar xvzf hugo_0.18.1_Linux-64bit.tar.gz
- mkdir -p $GOPATH/bin
- cp hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 $GOPATH/bin/hugo
script: hugo -t casper
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: osgav.run
  region: eu-central-1
  endpoint: osgav.run.s3-website.eu-central-1.amazonaws.com
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: osgav/osgav-blog
