language: go
go:
- 1.4
install:
- export HUGO_DOWNLOAD=0.18.1
- wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_DOWNLOAD}/hugo_${HUGO_DOWNLOAD}_Linux-64bit.tar.gz
- tar xvzf hugo_${HUGO_DOWNLOAD}_Linux-64bit.tar.gz
- mkdir -p $GOPATH/bin
- cp hugo_${HUGO_DOWNLOAD}_linux_amd64/hugo_${HUGO_DOWNLOAD}_linux_amd64 $GOPATH/bin/hugo
script: hugo -t casper
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: osgav.run
  region: eu-central-1
  endpoint: osgav.run.s3-website.eu-central-1.amazonaws.com
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: osgav/osgav-blog
