baseurl = "https://osgav.run/"
languageCode = "en-us"
title = "osgav"
theme = "casper"
paginate = 5
uglyurls = true
enableEmoji = true
preserveTaxonomyNames = true

[params]
	description = "systems engineer interested in operations, security, development, linux, automation, monitoring, python & bots"
	cover = "images/headimgr.jpg"
	author = "osgav"
	authorlocation = "the internet"
	authorwebsite = "https://osgav.run/"
	bio = "Systems Engineer"
	logo = "images/tux.jpg"
	hideHUGOSupport = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
	name = "blog"
	post = "<span class=\"icon-edit\"></span>"
	pre = "<h4 class=\"menutitle\"><span class=\"icon-cog\"></span> osgav</h4>"
	weight = -100
	identifier = "blog"
	url = "/"

[[menu.main]]
	name = "tags"
	post = "<span class=\"icon-tag\"></span>"
	weight = -80
	identifier = "tags"
	url = "/tags.html"

[[menu.main]]
	name = "photos"
	pre = "<br /><h4 class=\"menutitle\"><span class=\"icon-website\"></span> outside</h4>"
	post = "<span class=\"icon-image\"></span>"
	weight = 90 
	url = "https://outside.osgav.run"

[[menu.main]]
	name = "twitter"
	pre = "<br /><h4 class=\"menutitle\"><span class=\"icon-search\"></span> connect</h4>"
	post = "<span class=\"icon-twitter\"></span>"
	url = "https://twitter.com/ZER0D0TS"
	weight = 110

[[menu.main]]
	name = "github"
	post = "<span class=\"icon-github\"></span>"
	url = "https://github.com/osgav"
	weight = 120

[[menu.main]]
    name = "site rss"
	post = "<span class=\"icon-feed\"></span>"
	url = "/index.xml"
	weight = 130
