baseurl = "https://osgav.run/"
languageCode = "en-us"
title = "osgav"
theme = "casper"
paginate = 5
uglyurls = true

[params]
	description = "systems engineer interested in operations, security, development, linux, automation, monitoring, python & bots"
	cover = "images/headimg.jpg"
	author = "osgav"
	authorlocation = "the internet"
	authorwebsite = "https://osgav.run/"
	bio = "Global Availability & Performance Engineer"
	logo = "images/tux.jpg"
	githubName = "osgav"
	twitterName = "ZER0D0TS"
	hideHUGOSupport = false

[[menu.main]]
	name = "$ curl https://blog"
	pre = "<h4>$ osgav</h4>"
	weight = -100
	identifier = "blog"
	url = "/"

[[menu.main]]
	name = "photo blog"
	pre = "<h4>$ outside</h4>"
	post = "<span class=\"icon-image\"></span>"
	weight = 90 
	url = "https://outside.osgav.run"

[[menu.main]]
	name = "github"
	pre = "<h4>$ find</h4>"
	post = "<span class=\"icon-github\"></span>"
	url = "https://github.com/osgav"
	weight = 110

[[menu.main]]
	name = "twitter"
	post = "<span class=\"icon-twitter\"></span>"
	url = "https://twitter.com/ZER0D0TS"
	weight = 110
